[package]
name = "bevy-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13" }
bevy_egui = "0.26"
rfd = "0.14.1"
serde = "1.0.197"
serde_json = "1.0.114"
